### ISSUE TITLE
Add cw-storage, cleaner structure

### ISSUE THREAD

**Issue by ethanfrey** [confio/cosmwasm-template#23]
With cosmwasm 0.6.1, let's enhance the template.

1. Use `cw-storage` to handle the data persistence layer, to give a good example of how that works
2. Break `contract.rs` into a few files. `msg.rs` will hold all data structures for the api, `state.rs` will hold all internal state structs, as well as cw-storage wrappers (Singleton, Typed/PrefixedStorage). `contract.rs` can then just hold the high-level business logic, which is nice for larger contracts so they are no unweildy.

**Comment by clevinson** [comment]
Happy to take this. Please assign :)

**Comment by ethanfrey** [comment]
Great. One comment on how I do it...

Editing the template directly is annoying to test (but the CI will check it). What I suggest is the following:

Generate a contract (foo) with the `cargo generate` command, then add with `git init`, commit, etc.Then edit that as desired and test with cargo as normal. When happy, `git diff` and copy/paste the changed lines.

At least that is how I do it.
