### ISSUE TITLE
Update wasm-bindgen

### ISSUE THREAD

**Issue by ethanfrey** [confio/cosmwasm-template#9]
I just updated cosmwasm-opt to a newer build system: https://github.com/confio/cosmwasm-opt/commit/af34cbb67d0122775da5d6f04faed66555bbeee1

As soon as this is published to dockerhub under the 0.5.2 tag, we should update the build process.

This requires the following in `Cargo.toml`:

```
[dependencies]
# needed for wasm-pack build process
wasm-bindgen = "0.2.55"
```

We also need to update the Readme. Maybe good to update existing examples as well

**Comment by webmaster128** [comment]
@ethanfrey Can you tag the updates of cosmwasm-opt? I don't see anything at https://hub.docker.com/r/confio/cosmwasm-opt/tags

**Comment by ethanfrey** [comment]
I pushed the 0.5.2 one, which should the 0.6 as well
